#
# Continuous Integration Workflow for libseccomp
#
# Copyright (c) 2020 Oracle and/or its affiliates.
# Author: Tom Hromatka <tom.hromatka@oracle.com>
#

#
# This library is free software; you can redistribute it and/or modify it
# under the terms of version 2.1 of the GNU Lesser General Public License as
# published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
# for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, see <http://www.gnu.org/licenses>.
#

name: Continuous Integration
on: ["push", "pull_request"]

jobs:
  amd64:
    name: amd64
    runs-on: ubuntu-20.04

    steps:
    - name: Install dependencies
      run: sudo apt-get install build-essential valgrind clang-tools lcov gperf astyle codespell
    - name: Install python dependencies
      run: |
        sudo apt-get install -y python3.6 python3-distutils python3-setuptools python3-pip
        python3 -m pip install --upgrade pip
        python3 -m pip install cython
        # Add cython to the path
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
        which python
        python --version
    - name: Checkout from github
      uses: actions/checkout@v2
    - name: Configure and build
      run: |
        ./autogen.sh
        ./configure --enable-python
        make check-build
    - name: Run tests
      run: LIBSECCOMP_TSTCFG_STRESSCNT=5 make check
    - name: Run live tests
      run: LIBSECCOMP_TSTCFG_TYPE=live LIBSECCOMP_TSTCFG_MODE_LIST=c make -C tests check
    - name: Run scan-build
      run: |
        make clean
        ./configure
        scan-build --status-bugs make
    - name: Run code coverage
      run: |
        make clean
        ./configure --enable-code-coverage
        make test-code-coverage
        lcov -c --exclude tools --exclude src/arch-syscall-check.c -d . > lcov.info
    - name: Upload code coverage results
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./lcov.info
